version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: prisoner
    environment:
      MYSQL_ROOT_PASSWORD: phatdev
      MYSQL_DATABASE: prisoner
      MYSQL_USER: phatdev
      MYSQL_PASSWORD: phatdev
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network

volumes:
  mysql-data:

networks:
  mysql-network:
    driver: bridge
